// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ID          pgtype.UUID
	Name        string
	Description string
	JoinCode    string
	TeacherID   pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Flashcard struct {
	ID         pgtype.Int4
	Front      string
	Back       string
	SetID      int32
	UserID     int32
	IsMastered bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type FlashcardSet struct {
	ID          pgtype.Int4
	Name        string
	Description string
	UserID      int32
	ClassID     int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
